#!/usr/bin/env bash
# displays subdomain info

dig_info () {
    ANSWER=$(dig "$1"."$2" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $0}')
    echo "The subdomain $1 is a $(echo $ANSWER | awk '{print $4}') record and points to $(echo $ANSWER | awk '{print $5}')"
}

if [[ $# == 1 ]]; then
    dig_info "www" "$1"
    dig_info "lb-01" "$1"
    dig_info "web-01" "$1"
    dig_info "web-02" "$1"
else
    dig_info "$2" "$1"
fi
