#!/usr/bin/env bash
# Configures your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'

chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo -e "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }

        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;

        error_page 404 /404.html;

        add_header X-Served-By \$hostname;

}" > /etc/nginx/sites-available/default

service nginx restart
