#!/usr/bin/env bash
# This script will change the IP of localhost nd facebook.com.
cp /etc/hosts ~/hosts.new
echo -e "127.0.0.2       localhost\n8.8.8.8         facebook.com" > ~/hosts.new
cp -f ~/hosts.new /etc/hosts
