#!/usr/bin/env bash
# configures how nginx will run
pkill apache2
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
su nginx -c 'service nginx restart'"
